### ISSUE TITLE
What things do you want to query?

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/graphql#1]
What things would you find especially useful to be able to query from applications? _Discuss!_

**Comment by aaronschachter** [comment]
Gambit Admin:
* User view: Query Rogue to find total # of Signups (as well as total # of completed Campaigns)
* Broadcast view: Query Rogue signups to find yes responses to a broadcast

**Comment by sohaibhasan** [comment]
Biggest value add for me would be the ability to query sources that haven't been integrated into quasar yet, for instance, every sms message of a certain topic by folks who have done more than X number of campaigns.
